// Code generated by "stringer -type=ResponseMessage"; DO NOT EDIT.

package constant

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LoginPasswordMismatch-0]
	_ = x[LoginUnverified-1]
	_ = x[RegisterEmailUsed-2]
	_ = x[EmailNotFound-3]
	_ = x[VerifyOtpExpired-4]
	_ = x[UserAlreadyVerified-5]
	_ = x[LogoutSuccess-6]
	_ = x[LoginSuccess-7]
	_ = x[RegisterSuccess-8]
	_ = x[VerifyOtpSuccess-9]
	_ = x[ResendOtpSuccess-10]
	_ = x[UserNotFound-11]
	_ = x[CreateUser-12]
	_ = x[UpdateUser-13]
	_ = x[DeleteUser-14]
	_ = x[GetDetailUser-15]
	_ = x[GetListUser-16]
}

const _ResponseMessage_name = "LoginPasswordMismatchLoginUnverifiedRegisterEmailUsedEmailNotFoundVerifyOtpExpiredUserAlreadyVerifiedLogoutSuccessLoginSuccessRegisterSuccessVerifyOtpSuccessResendOtpSuccessUserNotFoundCreateUserUpdateUserDeleteUserGetDetailUserGetListUser"

var _ResponseMessage_index = [...]uint8{0, 21, 36, 53, 66, 82, 101, 114, 126, 141, 157, 173, 185, 195, 205, 215, 228, 239}

func (i ResponseMessage) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ResponseMessage_index)-1 {
		return "ResponseMessage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResponseMessage_name[_ResponseMessage_index[idx]:_ResponseMessage_index[idx+1]]
}
